emp_manage/api/urls.py
from rest_framework.routers import DefaultRouter

from .views import EmployeeViewSet

router = DefaultRouter()
router.register(r'employees', EmployeeViewSet, basename='employees')
urlpatterns = router.urls

emp_manage/urls.py
from django.urls import path
from . import views as emp

app_name = 'emp_manage'

urlpatterns = [
    path('add',emp.EmployeeAddView.as_view(),name='add_employee'),
    path('list',emp.EmployeeListView.as_view(),name='list_employee'),
    path('edit/<int:pk>',emp.EmployeeEditView.as_view(),name='edit_employee'),
    path('delete/<int:pk>',emp.EmployeeDeleteView.as_view(),name='delete_employee')
]

employee/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from emp_manage.views import HomeView

urlpatterns = [
    path('',HomeView.as_view(),name='dashboard'),
    path('employee/',include('emp_manage.urls')),
    path('api/v1/',include('emp_manage.api.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

emp_manage/models.py
from django.db import models
from django.conf import settings

"""
Since we do not need login/authentication for employees,
using custom Employee model rather than using django.contrib.auth.models.User
"""

class Designation(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Employee(models.Model):
    employee_number = models.CharField(max_length=255,unique=True)
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=254,unique=True)
    address = models.CharField(max_length=500)
    photo = models.ImageField(upload_to='emp_photos',null=True,blank=True,help_text=f'Maximum file size is {settings.IMAGE_MAX_UPLOAD_SIZE} MB')
    designation = models.ForeignKey(Designation,on_delete=models.CASCADE)

emp_manage/forms.py
from django.forms import ModelForm,ImageField
from django.conf import settings

from .models import Employee

class EmployeeAddForm(ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'
    
    def clean_photo(self):
        photo = self.cleaned_data['photo']
        if photo:
            size = photo.size
            max_size = (settings.IMAGE_MAX_UPLOAD_SIZE*1024*1024)
            if size > max_size:
                self.add_error('photo',f'Maximum file size is {settings.IMAGE_MAX_UPLOAD_SIZE} MB')
        return photo

emp_manage/api/views.py
from rest_framework.viewsets import ModelViewSet

from emp_manage.models import Employee

from .serializers import EmployeeSerializer

class EmployeeViewSet(ModelViewSet):
    model = Employee
    serializer_class = EmployeeSerializer

    def get_queryset(self):
        return self.model.objects.all()

emp_manage/views.py
from copy import deepcopy

from django.shortcuts import render,get_object_or_404
from django.urls import reverse
from django.views import View
from django.views.generic.edit import FormView,DeleteView
from django.views.generic.list import ListView
from django.db.models import Count

from .forms import EmployeeAddForm
from .models import Designation, Employee

class HomeView(View):
    template_name = 'emp_manage/dashboard.html'
    model = Employee

    def get_queryset(self):
        qs = self.model.objects.values('designation__name').annotate(dcount=Count('designation__name')).order_by('designation__name')
        all_designations = deepcopy(Designation.objects.values_list('name',flat=True))
        count_data = {}
        for items in qs:
            count_data[items['designation__name']] = items['dcount']

        for designation in all_designations:
            if designation not in count_data:
                count_data[designation] = 0
        return count_data

    def get(self,request,*args,**kwargs):
        context = {}
        context['title'] = context['section_title'] = context['page_title'] = 'Dashboard'
        context['object_list'] = self.get_queryset()
        return render(request,self.template_name,context)

class EmployeeAddView(FormView):
    template_name = 'common_form.html'
    form_class = EmployeeAddForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'].buttons = [
            {'label':'Submit','type':'submit','class':'btn btn-primary float-right'}
        ]
        context['page_title'] = 'Add Employees'
        context['page_header'] = {
            'icon' : '<i class="nav-icon fas fa-user-plus"></i>',
            'title' : 'Add Employees'
        }
        return context
    
    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('emp_manage:list_employee')

class EmployeeListView(ListView):
    model = Employee
    template_name = 'data_table.html'
    ordering = '-id'

    headers = {
        'employee_number' : 'Employee Number',
        'name' : 'Name',
        'email' : 'Email',
        'address' : 'Address',
        'designation__name' : 'Designation',
        'actions' : 'Actions'
    }
    field_list = [
        'id',
        'employee_number',
        'name',
        'email',
        'address',
        'designation__name'
    ]

    def get_queryset(self):
        queryset = deepcopy(super().get_queryset().values(*self.field_list))
        for qs in queryset:
            qs['actions'] = [
                {'label' : 'Edit', 'href' : reverse('emp_manage:edit_employee',kwargs={'pk':qs['id']}), 'class' : 'btn text-primary ml-1'},
                {'label' : 'Delete', 'href' : reverse('emp_manage:delete_employee',kwargs={'pk':qs['id']}), 'class' : 'btn text-danger ml-1 emp-delete-btn'},
            ]
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['headers'] = self.headers
        context['page_title'] = 'Employee List'
        context['page_header'] = {
            'icon' : '<i class="nav-icon fas fa-table"></i>',
            'title' : 'Employee List'
        }
        context['value_as_action'] = ['actions']
        return context

class EmployeeEditView(EmployeeAddView):
    def get_form_kwargs(self):
        form_kwargs = super().get_form_kwargs()
        form_kwargs['instance'] = get_object_or_404(Employee,id=self.kwargs['pk'])
        return form_kwargs
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'].buttons = [
            {'label':'Submit','type':'submit','class':'btn btn-primary float-right'}
        ]
        context['page_title'] = 'Edit Employee'
        context['page_header'] = {
            'icon' : '<i class="nav-icon fas fa-edit"></i>',
            'title' : 'Edit Employee'
        }
        context['breadcrumbs'] = {
            reverse('emp_manage:list_employee') : 'Employee List'
        }
        return context

class EmployeeDeleteView(DeleteView):
    model = Employee
    template_name = 'emp_manage/delete_employee.html'
    
    def get_success_url(self):
        return reverse('emp_manage:list_employee')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Delete Employee'
        context['page_header'] = {
            'icon' : '<i class="nav-icon fas fa-trash"></i>',
            'title' : 'Delete Employee'
        }
        context['breadcrumbs'] = {
            reverse('emp_manage:list_employee') : 'Employee List'
        }
        return context

emp_manage/templates/emp_manage/dashboard.html
{% extends 'base.html' %}
{% block title %} {{title}} {% endblock %}

{% block content %}
<section class="content">
    <div class="container-fluid">
      <div class="row">
        {% for designation,count in object_list.items %}
        <div class="col-lg-3 col-6">
          <div class="small-box bg-info">
            <div class="inner">
              <h3>{{count}}</h3>

              <p>{{designation}}</p>
            </div>
            <div class="icon">
              <i class="ion ion-person"></i>
            </div>
            <a href="{% url 'emp_manage:list_employee' %}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
</section>
{% endblock %}

emp_manage/templates/emp_manage/delete_employee.html
{% extends 'base.html' %}

{% block title %} {{page_title}} {% endblock %}

{% block content %}
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="card">
                    <div class="card-header">
                        <h4>{{page_header.icon|safe}} {{page_header.title|safe}}</h4>
                    </div>
                    <div class="card-body">
                        <h3>{{employee.name}}</h3>
                        <h6>#{{employee.employee_number}} | {{employee.designation.name}}</h6>
                        <h6>{{employee.email}}</h6>
                    </div>
                    <div class="card-footer">
                        <form action="{{equest.path}}" method="post">
                            {% csrf_token %}
                            <div class="text-center">
                                <p class="text-danger">This action can not be undone. Are you sure to delete ?</p>
                                <a class="btn btn-success ml-1" href="{% url 'emp_manage:list_employee' %}">Cancel</a>
                                <button class="btn btn-danger ml-1" type="submit">Yes, Delete Now</button>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

employee/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Employee Management | {% block title %}Dashboard{% endblock %}</title>

  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <link rel="stylesheet" href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/jqvmap/jqvmap.min.css' %}">
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/daterangepicker/daterangepicker.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.min.css' %}">
  {% block stylesheet %}{% endblock %}
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'dashboard' %}" class="nav-link">Home</a>
      </li>
    </ul>

  </nav>
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <a href="{% url 'dashboard' %}" class="brand-link">
      <img src="{% static 'dist/img/AdminLTELogo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">Employees</span>
    </a>
    <div class="sidebar">
      <nav class="mt-2">
        {% include 'left_sidebar.html' %}
      </nav>
    </div>
  </aside>
  <div class="content-wrapper">
    <div class="content-header">
		<div class="container-fluid">
			<div class="row mb-2">
			<div class="col-sm-6">
        {% if section_title %}
          <h1 class="m-0">{{section_title}}</h1>
        {% endif %}
			</div>
			<div class="col-sm-6">
				<ol class="breadcrumb float-sm-right">
				<li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
				{% for link,label in breadcrumbs.items %}
					<li class="breadcrumb-item"><a href="{{link}}">{{label}}</a></li>
				{% endfor %}
				<li class="breadcrumb-item active">{{page_title}}</li>
				</ol>
			</div>
			</div>
		</div>
    </div>
	{% block content %}{% endblock %}
  </div>
  <footer class="main-footer">
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.2.0
    </div>
  </footer>
</div>
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<script src="{% static 'plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'plugins/daterangepicker/daterangepicker.js' %}"></script>
<script src="{% static 'plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<script src="{% static 'plugins/summernote/summernote-bs4.min.js' %}"></script>
<script src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<script src="{% static 'dist/js/adminlte.js' %}"></script>
<script src="{% static 'dist/js/pages/dashboard.js' %}"></script>
{% block javascript %}{% endblock %}
</body>
</html>

employee/templates/common_form.html
{% extends 'base.html' %}

{% load formtags %}
{% load widget_tweaks %}

{% block title %} {{page_title}} {% endblock %}

{% block content %}
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="card">
                    <div class="card-header">
                        <h4>{{page_header.icon|safe}} {{page_header.title|safe}}</h4>
                    </div>
                    <div class="card-body">
                        <form action="{{from.action|default:request.path}}" role="form" id="{{form.id|default:'id_form'}}" method="{{form.method|default:'post'}}" enctype="multipart/form-data" novalidate>
                            <!-- CSRF TOKEN -->
                            {% csrf_token %}
                
                            <!-- Hidden fields -->
                            {% for hidden_field in form.hidden_fields %}
                                {{ hidden_field }}
                                {% if hidden_field.errors %}
                                    {% for error in hidden_field.errors %}
                                    <div class="alert alert-danger" role="alert">
                                        {{ error }}
                                    </div>
                                    {% endfor %}
                                {% endif %}
                            {% endfor %}
                
                            <!-- Non field errors -->
                            {% if form.non_field_errors %}
                                {% for error in form.non_field_errors %}
                                <div class="alert alert-danger" role="alert">
                                    {{ error }}
                                </div>
                                {% endfor %}
                            {% endif %}
                
                            <!-- Rendering Feilds -->
                            {% for field in form.visible_fields %}
                            <div class="form-group">
                                {{ field.label_tag }}
                                {% render_field field class=form|validate_class:field placeholder=field.label autocomplete='off' %}
                                {% validate_error field %}
                                {% field_help_text field %}
                            </div>
                            {% endfor %}

                            <!-- Buttons -->
                            <div class="mt-4">
                                {% for button in form.buttons %}
                                    <button {% for key,value in button.items %} {{key}} ="{{value}}" {% endfor %}>
                                        {{button.label|safe}}
                                    </button>
                                {% endfor %}
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

employee/templates/common_table.html
{% load tabletags %}

<table id="commonTable">
    <thead>
        <tr>
            {% for header in headers.values %}
                <th>{{header}}</th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
        {% for data in object_list %}
            <tr>
                {% for key in headers.keys %}
                    {% if key in value_as_action %}
                        <td class="d-flex">{% getaction data key %}</td>
                    {% else %}
                        <td>{{data|getattribute:key}}</td>
                    {% endif %}
                {% endfor %}
            </tr>
        {% endfor %}
    </tbody>
</table>

employee/templates/data_table.html
{% extends 'base.html' %}

{% block title %} {{page_title}} {% endblock %}

{% block stylesheet %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.css">
{% endblock %}

{% block content %}
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h4>{{page_header.icon|safe}} {{page_header.title|safe}}</h4>
                    </div>
                    <div class="card-body">
                        {% include 'common_table.html' %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block javascript %}
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.js"></script>
    <script type="text/javascript">
            $(document).ready( function () {
                $('#commonTable').DataTable();
            } );
    </script>
{% endblock %}

employee/templates/left_sidebar.html
<ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
    <li class="nav-item active">
      <a href="{% url 'dashboard' %}" class="nav-link">
        <i class="nav-icon fas fa-tachometer-alt"></i>
        <p>Dashboard</p>
      </a>
    </li>
    <li class="nav-item active">
      <a href="{% url 'emp_manage:add_employee' %}" class="nav-link">
        <i class="nav-icon fas fa-user-plus"></i>
        <p>Add Employee</p>
      </a>
    </li>
    <li class="nav-item active">
      <a href="{% url 'emp_manage:list_employee' %}" class="nav-link">
        <i class="nav-icon fas fa-table"></i>
        <p>Employee List</p>
      </a>
    </li>
  </ul>